#!/usr/bin/env php

<?php

use ecoAPM\LibYear\Factory;

const vendor_indicator = 'vendor' . DIRECTORY_SEPARATOR . 'ecoapm' . DIRECTORY_SEPARATOR . 'libyear';
$is_vendored = strpos(__DIR__, vendor_indicator) === strlen(__DIR__) - strlen(vendor_indicator);
require_once __DIR__ . ($is_vendored ? '/../../..' : '') . '/vendor/autoload.php';

Factory::app()->run($argv);
